### ISSUE TITLE
Practica de compuertas lógicas

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/compuertas-logicas-equipo-jeanette-arlet-salazar-nicolas#2]
[Practica Compuertas logicas .pdf](https://github.com/SistemasTecTlaxiaco/compuertas-logicas-equipo-jeanette-arlet-salazar-nicolas/files/7724608/Practica.Compuertas.logicas.pdf)

**Comment by Julissamigdalia** [comment]
El trabajo está bien, solo faltó la descripción de las figuras  19/20

**Comment by Julissamigdalia** [comment]
El trabajo está bien, solo faltó la descripción de las figuras
29/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado
